# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 978ef59343b146659ad6798c65c4a35be35f4c6d148591da5e31f60fc36b1fafb8dfb1a8f61fbb95ff1f41088f91ec6d5609b5fe289be49bd6b6b628ee5922e7

test:
  secret_key_base: 43a4aa4ff3e689711777040e91d79274f12c055eb80ca0626f40fb23bfbbfcdf60f42564865d25abf9da5465a45f573cf5adec81fe6cdf4bc19cb8f7d5864e39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
